### ISSUE TITLE
main.py, line 49, references undefined "spectra"

### ISSUE THREAD

**Issue by texadactyl** [luigifcruz/turboseti-stream#2]
Missing a spectra parameter?

**Comment by texadactyl** [comment]
Also, line 136 has an unnecessary semicolon.

**Comment by texadactyl** [comment]
Instead of from ```from turbo_seti.find_doppler.kernels import *``` (dangerous in Python), why not name the things that you wish to import?  Then, you can get the benefit of linting your code (pylint or use your IDE).

**Comment by wfarah** [comment]
@texadactyl We should add you as contributor

**Comment by texadactyl** [comment]
@wfarah Huh, who me???

**Comment by texadactyl** [comment]
Line 56 - shoulder_size is always 0.
